version: '2'
services:
  factorio:
    image: 'dbarranco/factorio:0.16.8'
    volumes: 
       - 'factorio_saves:/opt/factorio/saves'
       - 'factorio_mods:/opt/factorio/mods'
    ports:
      - '34197:34197/udp'
      - '27015'
volumes:
  factorio_saves:
    driver: local
  factorio_mods:
    driver: local
